vscode-shellcheck/vscode-shellcheck

package.json, src/linter.ts
Setting is `useWorkspaceRootAsCwd` (boolean). The rationale for this is that ShellCheck source directives may be specified as relative to the root of the workspace, which is more compatible with the behaviour of many other editors when used in conjunction with ShellCheck.
For example, Vim might be launched from the root of the workspace, and ShellCheck will be able to follow the source directives consistently by being anchored from the root path under which it was launched. This in turn means the editor doesn't have to always launch ShellCheck under the directory of the file to be linted, and that source directives do not have to be always relative to the location of each individual file.
The setting is disabled by default, in which case the existing behaviour is retained. This is to set …
=> Add setting to always launch ShellCheck with the workspace root as cwd

.gitignore, bindl.config.js, package.json, src/linter.ts, yarn.lock
The binaries are downloaded with [`bindl`](https://github.com/felipecrs/bindl), which I just wrote. It basically only requires a config file, so take a look at the `bindl.config.js`.
[shellcheck-0.9.0.vsix.zip](https://github.com/timonwong/vscode-shellcheck/files/5113578/shellcheck-0.9.0.vsix.zip)
Fixes #71
=> feat: ship binaries with the extension

src/linter.ts
We don't want ARM users to use the x86 version of the binary, right?
=> chore: Use x32 binary for Windows only if x32 or x64

.github/dependabot.yml
We don't want to update VSCode or Node version to keep the compatibility.
=> chore(dependabot): ignore @types/node and @types/vscode

src/linter.ts
When bundled binaries are not available.
Fixes: #244
=> fix: not loading `shellcheck` from `PATH` when the bundled is not available

.editorconfig, .eslintrc, .github/dependabot.yml, .github/workflows/ci.yaml, .vscode/launch.json, .vscode/spell.json, package.json, src/linter.ts, test/runTest.ts, test/suite/fix-all.test.ts, yarn.lock
Also:
- Bump bindl to v2, as this allows us to install the dependencies and
develop on Windows natively.
- Add Windows to the matrix of operating systems to test in CI. This way
we can assure the extension is working on Windows.
- Adjust test executor so it allows setting different versions of VS
Code to test using an environment variable VSCODE_TEST_VERSION.
- Add matrix of VS Code versions to test in CI, so we can assure that
we are not breaking the extension for the oldest supported VS Code
version (currently 1.38.1, which uses Node 10).
- Change the default version of Node in CI to 14, as it's the current
LTS, and the current VS Code (1.58.2) also uses it internally, and
also because this version does not matter, as the extension will be
tested against old versions of VS Code …
=> fix: loading bundled binary on Windows `ia32` arch

README.md, package.json
Was wondering why my jnoortheen.xonsh vscode editor extension was showing shellcheck  errors vs the xonsh IDE ones and stuff. I then realized the default doesn't exclude the xonsh shell type files for shellcheck. 
This PR will exclude those files so that having both installed will not show the shellcheck errors when editing xonsh scripts and rc files.
Reference:
https://xon.sh/bash_to_xsh.html
"For shell scripts, the recommended file extension is xsh, and shebang line is #!/usr/bin/env xonsh."
=> feat: ignore Xonsh scripts

.prettierrc
I noticed the [vscode-prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension wasn't working out of the box. The root cause was that there was no Prettier configuration file.
=> format: add prettier config

src/linter.ts, src/parser.ts, test/suite/extension.test.ts
Add a link to the [ShellCheck Wiki](https://www.shellcheck.net/wiki/Home) when you hover a ShellCheck error/warning.
* We already had a `Show ShellCheck wiki for ...` code action but that requires an extra click
* More info at https://code.visualstudio.com/api/references/vscode-api#Diagnostic
(lint id is clickable)
=> feat: provide inline links to wiki on hover

README.md, doc/API.md, src/api.ts, src/extension.ts, src/linter.ts
This PR introduces [an API endpoint](https://github.com/claui/vscode-shellcheck/blob/6f94d4fcd446fe9068ebb3bf3024097ea6a96769/doc/API.md) to the ShellCheck extension.
```ts
export interface ShellCheckExtensionApiVersion1 {
registerDocumentFilter: (documentFilter: DocumentFilter) => Disposable;
}
```
Other VS Code extensions can use that API to tell the ShellCheck extension about shell-based domain-specific languages (DSLs) whose language ID is not `shellscript`.
This enables linting for all text documents that match the filter, especially derived languages whose language IDs are not `shellscript`.
There are a couple of such DSLs, e.g. [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) files.  
If a third-party extension supports such a domain-specific language, it makes sense for that …
=> feat: allow linting for domain-specific shell languages

README.md, package.json, src/linter.ts
This PR adds the `output` scheme to the default `shellcheck.ignoreFileSchemes` list.
If `shellcheck.run` is set to `onType` (the default), writing to the log may cause an endless feedback loop: VS Code treats the output channel as a text document, and will emit a document-change event for every single line logged to any output channel, which in turn may lead to our handler logging even more lines, and so on.
This new check is arguably redundant: the language of the channel can never be Shell, which means the existing `isAllowedTextDocument` check happens to cover this case already, albeit by accident.
I still feel that there’s value in declaring this explicitly rather than relying on accidental behavior.
=> fix: prevent endless feedback loops

src/linter.ts
Creating named diagnostic collection correctly set the "owner" field.
Closes #666
=> fix: use named diagnostic collection

package.json
This improves the configuration description with a clearer example [as suggested](https://github.com/vscode-shellcheck/vscode-shellcheck/issues/740#:~:text=Exclude%20certain%20checks.%20For%20example%2C%20to%20exclude%20SC1017%2C%20enter%201017) by @LeuschkeTressa.
This doesn't yet implement input validation.
Closes #740
=> feat: improve some configuration descriptions

.github/dependabot.yml, .github/workflows/ci.yaml, package-lock.json, package.json
Because VS Code 1.66 comes with Node 16.
=> build(deps-dev): fix vscode and node version

bindl.config.js
=> fix: windows x86 (32 bits) vsix does not contain the binary

doc/API.md
We don't need the comment on the JSON flagged here; switch that block from json to jsonc.
=> docs: tweak syntax highlighting in API.md

src/settings.ts
With workaround until https://github.com/microsoft/vscode-vsce/issues/786 is not fixed.
Closes #824
=> build(deps): use x86 binary on windows for arm

bindl.config.js
Needed after https://github.com/vscode-shellcheck/shellcheck-binaries/pull/9
=> build: fix binaries url

package.json, snippets/snippets.json
[This](https://github.com/emilyseville7cfg-plugins/json-bash-language-server/blob/1e17a6d2dc9227431d83660016ae84ca94a11e21/vscode-client/snippets/convention.md) snippet naming convention is used.
=> feat: add snippets for directives

package.json, src/linter.ts
Partial #908
To activate, bring up the command palette and choose `ShellCheck: Collect Diagnostics For Current Document`
=> feat: add shellcheck.collectDiagnostics command 

package.json
Shellcheck doesn't support fish scripts, so they should be ignored
=> fix: add fish scripts to the default ignore patterns

package.json
Useful in situations like devcontainers, where someone would like to use an outdated version of the shellcheck binary.
=> feat: allow to disable version check on workspace

README.md
Also:
- Removing contributors list as it's outdated anyway, GitHub maintains an up to date list at the project's right side panel
Refs #1196
Refs #1194
=> docs: address some common questions

.prettierrc, package-lock.json, package.json
Use newer Node.js and NPM by default as well. It does not need to follow
vscode's. What matters is @types/node and @types/vscode being compatible
with the version of Node.js and VSCode being supported.
=> build(deps-dev): refresh dependencies

.github/workflows/ci.yaml, licenses/shellcheck-LICENSE.txt, src/settings.ts
Drop support for Windows 32 bits, since the Visual Studio Marketplace no longer accepts publishing extensions for such target.
Also update the shellcheck LICENSE to the latest version.
=> build(deps): drop support for Windows 32 bits

src/linkify.ts, test/linkify.test.ts
Thanks @TriMoon for the report and the detailed analysis.
Fixes #1558
=> fix: not linking comments without SC prefix

src/linter.ts
- Refs https://github.com/vscode-shellcheck/vscode-shellcheck/issues/920
- Refs https://github.com/vscode-shellcheck/vscode-shellcheck/issues/1541
- Refs https://github.com/vscode-shellcheck/vscode-shellcheck/issues/1091
- Refs https://github.com/vscode-shellcheck/vscode-shellcheck/issues/916
=> fix: should warn if ShellCheck integration in Bash IDE is enabled

bindl.config.mjs, package-lock.json, package.json
We no longer need to use https://github.com/vscode-shellcheck/shellcheck-binaries because bindl now supports downloading and extracting `.tar.xz` files out of the box without requiring native dependencies that were causing issues on some platforms.
- Refs https://github.com/felipecrs/bindl/pull/838
- Refs https://github.com/felipecrs/decompress-tarxz/pull/3
- Refs https://github.com/felipecrs/decompress-tarxz/pull/4
- Refs https://github.com/httptoolkit/xz-decompress/pull/11
=> build(deps): download binaries directly from shellcheck releases
