.vscode/settings.json
package-lock.json
src/linter.ts

Workaround: filter out virtual documents (ie. git)

---

README.md
package.json
src/linter.ts
src/utils/wslSupport.ts

Adds Windows Subsystem for Linux support
I have no idea what @rogalmic means by missing permissions. Maybe he tried pushing directly to the repo instead of a fork.

Add WSL support

---

.vscode/tasks.json
package.json
src/extension.ts
src/linter.ts

Fix shellcheck compatibility problem

---

src/utils/filematcher.ts

See https://github.com/timonwong/vscode-shellcheck/issues/15#issuecomment-393868194

Make ignorePatterns match things with a leading dot

---

README.md

Add help section for docker shellcheck

---

README.md
package-lock.json
package.json
src/linter.ts

Add diagnostic tags for unused

---

.travis.yml
package-lock.json
package.json
src/linter.ts
test/extension.test.ts

Substitute ${workspaceRoot} in "executablePath"

---

.vscode/tasks.json
src/linter.ts

Specify shell dialect on file ext

---

package.json
src/linter.ts

Add "shellcheck.ignoreFileSchemes" option

---

.azure-pipelines.yml
.travis.yml
.vscode/launch.json
package.json
src/linter.ts
src/utils/logger.ts
src/utils/tool-check.ts

Add shellcheck wiki link to code actions

---

.vscode/launch.json
package.json
src/linter.ts
src/utils/filematcher.ts

Fix ignorePatterns for non-workspace files

---

README.md
package.json
src/linter.ts
src/parser.ts
src/utils/path.ts
src/utils/tool-check.ts

Implement "auto fix" feature

---

package.json

Fix typing errors on package.json

---

src/linter.ts

fix: Builtin binaries not working

---

src/linter.ts
src/utils/tool-check.ts

chore: Adjust error message

---

.github/workflows/ci.yaml

https://github.com/cycjimmy/semantic-release-action#basic-usage

ci: use PAT GH_TOKEN to grant repo access

---

bindl.config.js

feat: add shellcheck binaries for Linux ARM

---

README.md
package.json

docs: add quick start GIF and adjust description

---

src/utils/tool-check.ts

fix: shellcheck command failed

---

README.md
package.json

feat: Enable the "Quick Fix" feature by default

---

src/utils/tool-check.ts

fix: timeout on shellcheck -V

---

bindl.config.js

https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md

build(deps): upgrade shellcheck from 0.7.1 to 0.7.2

---

src/linter.ts

fix: `executablePath` not being respected

---

package.json
yarn.lock

This dependency was not being used, and to upgrade the others I ran `yarn upgrade`.

build(deps): remove `bl` dependency and upgrade others

---

package.json
src/linter.ts
src/utils/async.ts
yarn.lock

This required an update to our async.ts, so I basically just copied the newest revision from:
https://github.com/microsoft/vscode/blob/73ae56b82b0fd268cab08e5903666025c1f6c335/extensions/php-language-features/src/features/utils/async.ts

build(deps-dev): bump typescript to 4.4.2

---

.github/workflows/ci.yaml
package-lock.json
package.json
src/fix-all.ts
test/suite/extension.test.ts
test/suite/fix-all.test.ts

So that at least a valid result is produced. But, it then would require
more manual triggers to fix the rest of the issues again.
This is a partial fix for #367.

fix: only fix one issue when multiples are found

---

src/linkify.ts

chore: fix linkify RE only works for first line

---

.vscodeignore
package.json

Refs https://code.visualstudio.com/updates/v1_68#_sponsoring-extensions

refactor: support sponsorship

---

src/linter.ts
src/utils/tool-check.ts

The property `executableNotFound` must always be consistent to `toolVersion`. One or the other can be truthy but not both at the same time. They’re also always updated together.
This PR converts them into a union type.  
That allows the type system to take care of internal consistency.

refactor: make mutually exclusive fields a union

---

src/linter.ts

Until now, the ShellCheck extension has supported a single set of preferences per workspace and assumed that those preferences should always hold for the entire workspace.
However, [VS Code supports settings on more levels](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence), for example folder-level settings and [language-specific settings](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings).
This PR adds missing support for both folder-level settings and language-specific settings.
For an overview on workspace-folder-level settings, see VS Code’s [documentation on multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings).
For a practical example, see the [`workspace-folder.test.ts` …

fix: honor folder-level and lang-specific settings

---

README.md
bindl.config.js

feat: add prebuilt shellcheck binary for apple m1 (from homebrew)

---

package.json
src/settings.ts

feat: validate user input for `shellcheck.exclude`

---

src/linter.ts
src/settings.ts
src/utils/path.ts

fix: ensure cwd exists before spawn shellcheck

---

.vscodeignore

fix: missing resource files

---

.github/FUNDING.yml

Signed-off-by: Timon Wong <timon86.wang@gmail.com>

docs: add patreon

---

package.json

fix: ignore patterns added in settings ui not being ignored

---

publish.release.config.js

fix: fix platform-specific publish

---

.github/workflows/ci.yaml
cspell.json
package-lock.json
package.json

- Refs https://github.com/microsoft/vscode-vsce/issues/786
- Refs https://github.com/felipecrs/semantic-release-vsce/pull/376
- Refs https://github.com/felipecrs/bindl/commit/bc69ed869f8d701c1513cc42494e92ec36051c6a
- Refs https://github.com/vscode-shellcheck/vscode-shellcheck/issues/845

feat: publish universal `vsix` without binaries

---

README.md
bindl.config.js
package-lock.json
package.json

build(deps): remove incorrect binary for Windows x86

---

cspell.json
snippets/snippets.json

I've prettified existing snippets to make them follow the same style as [these](https://github.com/github/vscode-github-actions/blob/a2f82688bd12a8a72c5197104ed759d637d2764d/snippets/snippets.json) ones.
Also I've added new snippets for optional checks and disabling all warnings at once. 😄

feat: prettify existing snippets and add new ones

---

.vscodeignore

fix: snippets folder not found

---

bindl.config.js
package.json
src/utils/tool-check.ts
tsconfig.json

Closes https://github.com/vscode-shellcheck/vscode-shellcheck/issues/1036

fix: align shellcheck version check with bundled binary

---

src/fix-all.ts
src/parser.ts

fix: fix all applying edits not owned by shellcheck

---

src/linter.ts

fix: cannot read properties of null

---

package.json

Among some other minor improvements.

fix: mention that `.shellcheckrc` should preferred in settings

---

README.md

Refs: https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
Closes #1371

docs: update auto-fix on save example for vscode 1.85+

---

bindl.config.mjs
package.json
src/parser.ts
src/utils/tool-check.ts
tsconfig.json

fix: decrease the minimum shellcheck version to 0.7.0

---

package.json
src/extension.ts
src/linter.ts
test/extension.test.ts

feat: add support for Bats
